//
//  ImageCache.swift
//  RedditSample
//
//  Created by Dmytro Chapovskyi on 07.10.2020.
//

import Foundation
import UIKit


//class ImageCache {
//
//	typealias Completion = (UIImage?) -> ()
//
//	let shared = ImageCache()
//
//	///
//	/// Contains downloaded images. Keys are generated by `key(url:)`
//	///
//	private var cache = NSCache<NSString, UIImage>()
//
//	///
//	/// Completions to execute on corresponding image load finish.
//	///
//	private var completions = [NSString: [Completion]]()
//
//	private init() { }
//
//	///
//	/// Keys are image URL absolute string.
//	///
//	private func key(_ url: URL) {
//
//	}
//}
